[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -I ../shared/include
  -I ../shared/generated
extra_scripts = pre:../tools/generate_web_assets.py
