[env:tenstar-esp32-c3-supermini-plus]
platform = espressif32
board = tenstar-esp32-c3-supermini-plus
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -I ../shared/include
  -I ../shared/generated
extra_scripts = pre:../tools/generate_web_assets.py
